package rando

import (
	"math"
	"math/rand"
	"time"
)

func StringN(length int) (s string) {
	if length < 0 {
		length = rand.Intn(100)
	}
	for i := 0; i < length; i++ {
		s += string(Uint8())
	}
	return
}

func String() (s string) {
	return StringN(-1)
}

// Strings returns a random size string slice with random length strings.
func Strings() (s []string) {
	return StringsQty(rand.Intn(math.MaxUint8))
}

// StringsQty returns a string slice with size `qty` with random length strings.
func StringsQty(qty int) (s []string) {
	if qty <= 0 {
		return nil
	}

	s = make([]string, qty)
	for i := 0; i < qty; i++ {
		s[i] = String()
	}
	return
}

// StringsQtyN returns a random size string slice up to size `qty` with random length strings.
func StringsQtyN(qty, n int) (s []string) {
	for i := 0; i < qty; i++ {
		s = append(s, StringN(n))
	}
	return
}

// StringsQN returns a random size string slice up to size `qty` with random length strings.
func StringsQN(q, n int) (s []string) {
	q = rand.Intn(q)
	for i := 0; i < q; i++ {
		s = append(s, StringN(n))
	}
	return
}

// StringsN returns a random size string slice with random strings of length `l`.
func StringsN(l int) (s []string) {
	qty := rand.Intn(math.MaxUint8)
	for i := 0; i < qty; i++ {
		s = append(s, StringN(l))
	}
	return
}

// StringsQtyLen returns a []string with size `qty` and set item lengths.
func StringsQtyLen(qty, length int, reseed ...int64) (result []string) {
	result, _ = StringsQtyLenSeed(qty, length, reseed...)
	return
}

// StringsQtyLenSeed returns a []string with size `qty` and set item lengths,
// that can be regenerated by reusing the same seed.
func StringsQtyLenSeed(qty, length int, reseed ...int64) (result []string, seed int64) {
	if qty < 0 {
		qty = 0
	}

	if length <= 0 {
		length = 0
	}

	if len(reseed) == 1 && reseed[0] != 0 {
		seed = reseed[0]
	} else {
		// Auto-generate seed if not provided.
		seed = time.Now().UnixNano()
	}

	r := rand.New(rand.NewSource(seed))
	result = make([]string, qty)
	for i := range result {
		b := make([]byte, length)

		_, _ = r.Read(b) // Generate arbitrary bytes.
		result[i] = string(b)
	}

	return
}
